version: 2
updates:
  - package-ecosystem: "bundler" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
        interval: "daily"
        timezone: "America/New_York"
        time: "10:30"
