source 'https://rubygems.org'

gem 'bundler'
gem 'faraday-retry'
gem 'jekyll'

gem 'classifier-reborn'
gem 'jekyll-archives'
gem 'jekyll-avatar'
gem 'jekyll-feed'
gem 'jekyll-include-cache'
gem 'jekyll-mentions'
gem 'jekyll-paginate'
gem 'jekyll-redirect-from'
gem 'jekyll-remote-theme'
gem 'jekyll-seo-tag'
gem 'jekyll-sitemap'
gem 'jemoji'
