source 'https://rubygems.org'

gem 'bundler', '2.2'
gem 'faraday-retry', '1.8'
gem 'jekyll', '4.3.3'

gem 'classifier-reborn', '2.0'
gem 'jekyll-archives', '2.1'
gem 'jekyll-avatar', '0.4'
gem 'jekyll-feed', '0.12'
gem 'jekyll-include-cache', '0.2'
gem 'jekyll-mentions', '1.4'
gem 'jekyll-paginate', '1.1'
gem 'jekyll-redirect-from', '0.14'
gem 'jekyll-remote-theme', '0.4'
gem 'jekyll-seo-tag', '2.6'
gem 'jekyll-sitemap', '1.4'
gem 'jemoji', '0.11'
